version: '3'
services:
  web:
    build:
      context: .
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=production_test_key
    volumes:
      - .:/payment_operations
    ports:
      - "80:80"
  pg:
    image: postgres:14
    ports:
      - "5490:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_operations
      - TZ=Asia/Kolkata
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
    command: ["-c", "max_connections=500"]
