development:
  host: pg
  adapter: postgresql
  encoding: unicode
  database: payment_operations
  pool: 10
  username: root
  password: password

production:
  host: pg
  adapter: postgresql
  encoding: unicode
  database: payment_operations
  pool: 10
  username: root
  password: password
